### ISSUE TITLE
Question: Kubernetes ingress

### ISSUE THREAD

**Issue by krakazyabra** [noobaa/noobaa-core#5902]
Hi! I would like to use nginx-ingress with noobaa-operator in k8s. 
How to set annotations properly (you are using websockets),what headers to use there? 

Thanks in advance

**Comment by guymguym** [comment]
Hi @krakazyabra 

We use websockets only for internal communication, but for ingress traffic we use plain https.

We haven't really experimented with Kubernetes Ingress yet (we only used Openshift Routes).
So you want to create an ingress for our two services `s3` and `noobaa-mgmt`.
Is there any specific ingress requirements that you require or just using the simple [single-service-ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress)

Thanks

**Comment by krakazyabra** [comment]
Hi @guymguym 
For experiments i'm using single-service
for now ingress for mgmt looks like 

<details>
 <summary>noobaa-mgmt.yaml</summary>

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: "noobaa-mgmt"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '500'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '500'
    nginx.ingress.kubernetes.io/send-timeout: "500"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  name: noobaa
spec:
  rules:
  - host: noobaa.domain.org
    http:
      paths:
      - path: /
        backend:
          serviceName: noobaa-mgmt
          servicePort: mgmt
  tls:
   - hosts:
     - noobaa.domain.org
status:
  loadBalancer:
    ingress:
    - {}
```

</details>
Seems, it's work fine
