### ISSUE TITLE
internal storage has no capacity(0 bytes) when using postgres as DB when running noobaa in docker

### ISSUE THREAD

**Issue by prembhaskal** [noobaa/noobaa-core#6904]
### Environment info
- NooBaa Version: **5.8**
- Platform: **docker**

### Actual behavior
I tried setting up the noobaa 5.8 in the docker with postgres as noobaa-db. The pods are all properly but the internal storage has no capacity. Hence I am unable to put any objects in the noobaa.
Keep the similar setup but using mongodb as the noobaa-db, the internal storage is created with 5GB capacity, so all put object works fine.

### Expected behavior
I expected that the noobaa internal capacity remains the same for both postgres and mongodb.

### Steps to reproduce
create the docker compose file with below content
```
version: '2.4'

services:

  noobaa-db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nbcore
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - noobaa-net


  noobaa-core:
    image: noobaa/noobaa-core:5.8.0
    container_name: noobaa-core
    restart: on-failure
    depends_on:
      - noobaa-db
    ports:
      - "9670:8080"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
      - "8446:8446"
      - "60100:60100"
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=noobaa-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CONTAINER_PLATFORM=DOCKER
      - JWT_SECRET=123
      - SERVER_SECRET=123
      - NOOBAA_ROOT_SECRET=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      - "AGENT_PROFILE={ \"image\": \"noobaa/noobaa-core:5.8.0\" }"
      - DISABLE_DEV_RANDOM_SEED=true
      - ENDPOINT_FORKS_NUMBER=1
      - OAUTH_AUTHORIZATION_ENDPOINT= 
      - OAUTH_TOKEN_ENDPOINT= 
      - NOOBAA_SERVICE_ACCOUNT= 
      - CONTAINER_CPU_REQUEST= 
      - CONTAINER_MEM_REQUEST= 
      - CONTAINER_CPU_LIMIT= 
      - CONTAINER_MEM_LIMIT= 
    networks:
    - noobaa-net

  noobaa-endpoint:
    image: noobaa/noobaa-core:5.8.0
    container_name: noobaa-endpoint
    depends_on:
      noobaa-db:
        condition: service_started
      noobaa-core:
        condition: service_started
    ports:
      - "6001:6001"
      - "6443:6443"
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=noobaa-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CONTAINER_PLATFORM=DOCKER
      - DISABLE_DEV_RANDOM_SEED=true
      - ENDPOINT_FORKS_NUMBER=1
      - 'MGMT_ADDR=wss://noobaa-core:8443'
      - 'MD_ADDR=wss://noobaa-core:8444'
      - 'BG_ADDR=wss://noobaa-core:8445'
      - 'HOSTED_AGENTS_ADDR=wss://noobaa-core:8446'
      - VIRTUAL_HOSTS= 
      - REGION=region1 
      - ENDPOINT_GROUP_ID=group1
      - LOCAL_MD_SERVER=true
      - LOCAL_N2N_AGENT=true
      - JWT_SECRET=123
      - NOOBAA_ROOT_SECRET=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      - NOOBAA_DISABLE_COMPRESSION=false
      - CONTAINER_CPU_REQUEST= 
      - CONTAINER_MEM_REQUEST= 
      - CONTAINER_CPU_LIMIT= 
      - CONTAINER_MEM_LIMIT= 
    command: >
      bash -c "sleep 30 &&
                echo '{ \"api\":\"system_api\",\"method\":\"create_system\", \"params\":{ \"name\":\"noobaa\",\"email\":\"admin@noobaa.io\",\"password\":\"123\" } }' > /tmp/myPayload.json &&
                echo $$(curl noobaa-core:8080/rpc -d @/tmp/myPayload.json) > /tmp/response.json &&
                echo $$(cat /tmp/response.json | grep -Eo '\"token\"[^,]*' | grep -Eo '[^:]*$$') > /tmp/token.json &&
                echo 'export NOOBAA_AUTH_TOKEN='$$(cat /tmp/token.json)'' >> /tmp/environment &&
                source /tmp/environment &&
                noobaa_init_files/noobaa_init.sh init_endpoint"
    networks:
    - noobaa-net

  start-noobaa:
    image: zablvit/zero
    container_name: start-noobaa
    depends_on:
      noobaa-db:
        condition: service_started
      noobaa-core:
        condition: service_started
      noobaa-endpoint:
        condition: service_started



networks:
  noobaa-net:
    driver: bridge
```

### More information - Screenshots / Logs / Other output
Please find screenshot of noobaa-mgmt UI.
![image](https://user-images.githubusercontent.com/3314241/157282542-514a3abb-d127-4502-aad3-768edcc70ecc.png)

Could you please inform if postgresDB is supported with docker platform? If yes, is there any specific option that needs to be provided to set a capacity for the internal storage.

Regards,
Prem
