### ISSUE TITLE
Noobaa endpoint crashes when spark write inside bucket

### ISSUE THREAD

**Issue by hector-vido** [noobaa/noobaa-core#6920]
I am using spark operator inside Openshift and every time spark tries to write inside the nooba S3 bucket, the noobaa endpoint crashes. The same does not happen with another storage class that give me a bucket based on CEPH radosgw.

### Environment info
- NooBaa Version: **Core 5.9.0/Operator 5.9.2**
- Platform: **Openshift 4.9.19/Kubernetes v1.22.3+2cb6068**
- Operator: **odf-operator.v4.9.4**

### Actual behavior
1. When spark writes inside the S3 bucket provisioned by noobaa, noobaa endpoint crashes.

### Expected behavior
1. Write the file successfully

### Steps to reproduce

I'm not a spark user, my prints are from another simple application, but this was the easiest application that I scripted that can reproduce the same problem.

- Install the spark-operator
- Create a configmap with the python script
- Create the bucketclaim
- Create the sparkapplication

1. Install the spark operator:

```bash
helm upgrade --install spark-operator spark-operator/spark-operator --namespace spark-operator --set image.tag=v1beta2-1.3.3-3.1.1 --set webhook.enable=true
```
2. Create a configMap named *s3write* with this python script: 

```python
import os
from pyspark.sql import SparkSession

if __name__ != '__main__':
    os.exit(0)

spark = SparkSession.builder.master('local').appName('PythonS3Write').getOrCreate()

s3_bucket = os.environ['BUCKET_NAME']

hadoopConf = spark.sparkContext._jsc.hadoopConfiguration()
hadoopConf.set('fs.s3a.endpoint', os.environ['S3_ENDPOINT_URL'])
hadoopConf.set('fs.s3a.access.key', os.environ['AWS_ACCESS_KEY_ID'])
hadoopConf.set('fs.s3a.secret.key', os.environ['AWS_SECRET_ACCESS_KEY'])
hadoopConf.set('fs.s3a.path.style.access', 'true')
hadoopConf.set('fs.s3a.connection.ssl.enabled', 'false')
hadoopConf.set('fs.s3a.impl', 'org.apache.hadoop.fs.s3a.S3AFileSystem')

dept = [
    ('Finance',10),
    ('Marketing',20),
    ('Sales',30),
    ('IT',40)
]
dept_columns = ['dept_name','dept_id']
df = spark.createDataFrame(data=dept, schema = dept_columns)

df.write.format('csv').save('s3a://' + s3_bucket + '/k8s/', mode='overwrite')

spark.stop()
```

```bash
oc create cm s3write --from-file s3write.py
```

3. Create the ObjectBucketClaim:

```yml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  finalizers:
  - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: spark-noobaa
  namespace: spark-operator
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: spark-noobaa-2fff7417-60d6-48aa-9645-7ec89a2cad68
  generateBucketName: spark-noobaa
  objectBucketName: obc-spark-operator-spark-noobaa
  storageClassName: openshift-storage.noobaa.io
``` 
```bash
oc create -f obc-nooba.yml
```

4. Create a CRD SparkApplication: 

```yml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-s3write
spec:
  type: Python
  sparkVersion: 3.1.1
  mainApplicationFile: 'local:///home/s3write.py'
  image: docker.io/hectorvido/pyspark-odh:s3.1.1-h3.2.0
  volumes:
    - name: s3write
      configMap:
        name: s3write
  imagePullPolicy: Always
  driver:
    serviceAccount: spark-operator
    env:
      - name: S3_ENDPOINT_URL
        valueFrom:
          configMapKeyRef:
            name: spark-noobaa
            key: BUCKET_HOST
      - name: BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            name: spark-noobaa
            key: BUCKET_NAME
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: spark-noobaa
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-noobaa
            key: AWS_SECRET_ACCESS_KEY
      - name: PYSPARK_MAJOR_PYTHON_VERSION
        value: "3"
    volumeMounts:
      - name: s3write
        mountPath: '/home/'
  executor:
    instances: 1
```
```bash
oc apply -f pyspark-s3write.yml
```
Observe the pod that never stop, and see the state of noobaa-endpoint with:

```bash
oc get pods -n openshift-storage
```

### More information - Screenshots / Logs / Other output

This image was created with these files: 
[image.tar.gz](https://github.com/noobaa/noobaa-core/files/8338283/image.tar.gz)

The logs are from nooba-endpoint, the application with noobaa bucket and radosgw bucket:
[noobaa-endpoint.log](https://github.com/noobaa/noobaa-core/files/8338277/noobaa-endpoint.log)
[spark-noobaa.log](https://github.com/noobaa/noobaa-core/files/8338279/spark-noobaa.log)
[spark-rgw.log](https://github.com/noobaa/noobaa-core/files/8338280/spark-rgw.log)

These screenshots are from another application, it is a little more complex because needs an upload, but the effect is the same as the one I wrote above:

![noobaa-endpoint-log](https://user-images.githubusercontent.com/39673799/159839971-1699dccc-4b26-4920-97a4-ca4af1d15b47.jpeg)
![01-routes-storageclass-buckets](https://user-images.githubusercontent.com/39673799/159838111-6754b453-1309-43c2-815d-61e8974641d9.png)
![02-rgw-upload](https://user-images.githubusercontent.com/39673799/159838115-c58e66ba-34c8-444c-a665-65ad1ef5e9f6.png)
![03-noobaa-upload](https://user-images.githubusercontent.com/39673799/159838118-103fdb9c-50ec-4e09-a1b9-5bff148a34b2.png)
![04-sparkapplication-rgw](https://user-images.githubusercontent.com/39673799/159838119-c43a5e32-7804-42da-b18a-62c23d54ee0f.png)
![05-sparkapplication-rgw-apply](https://user-images.githubusercontent.com/39673799/159838123-4b52e21b-14a9-4554-9d0b-f30008e1ba8a.png)
![06-sparkapplication-noobaa](https://user-images.githubusercontent.com/39673799/159838125-5ffa03ad-78df-46fc-a48f-3087a74d8dad.png)
![07-sparkapplication-noobaa-apply](https://user-images.githubusercontent.com/39673799/159838129-07b16010-9dfb-4c2f-9d8b-94a2666d67dc.png)
![08-noobaa-endpoint-crashloopback](https://user-images.githubusercontent.com/39673799/159838134-9b71c1b1-fe98-4455-ba4e-f81cc5532a45.png)
